Added a feature in mesa.time StagedActivation class
projectmesa/mesa pull request #1710
Opened 2023-06-03 07:49 UTC by subhamonsey

Suggested solution to issue #1709

Hi team Mesa, 

Right now the Staged Activation class only allows for functions executed at Agent level. However, one can well want to implement a function which is executed at model level (for ex, in an Economy, adjust the wage rate of all labourers, who are agents and share the same wage rate). Hence suggesting writing "model." before the function name in the object stage_list to indicate its a model level function.

2023-06-03 11:33 UTC, tpike3 requested changes
@subhamonsey This is great thanks! I have no issues with the code very clean and straighforward.

Could you make the following administrative adjustments: 
- make sure you use [Ruff so it passes the formatting test](https://github.com/projectmesa/mesa/blob/main/CONTRIBUTING.rst)
- put your commit message in the imperative so "Add feature in mesa.time StagedActivation"
- could you add a quick [useful snippet](https://github.com/projectmesa/mesa/blob/main/docs/useful-snippets/snippets.rst) maybe right after "Models with Discrete Time"; something like "Implementing Model Level Functions in Staged Activation"

Thanks again for identifying this features and adding it!

2023-06-03 12:33 UTC, rht commented
You can simplify the code into:
```python
        for stage in self.stage_list:
            if stage.startswith("model."):
                getattr(self.model, stage[6:])()
            else:
                for agent_key in agent_keys:
                    if agent_key in self._agents:
                        getattr(self._agents[agent_key], stage)()  # Run stage
            # We recompute the keys because some agents might have been removed
            # in the previous loop.
            agent_keys = list(self._agents.keys())
            if self.shuffle_between_stages:
                self.model.random.shuffle(agent_keys)
            self.time += self.stage_time
```

2023-06-03 13:25 UTC, rht commented
A different way of doing staged activation without abstraction:
```python
# Model step
def step(self):
    self.each_agents("stage1")
    self.shuffle_agents()
    self.adjust_wages()
    self.each_agents("stage2")
    self.shuffle_agents()
```

The `self.time` is not always needed in most cases. Sometimes. having fewer abstractions means it is more customizable, that the Mesa library's structure constraint doesn't get in the way of the user's model needs.

2023-06-03 13:52 UTC, rht commented
Random activation:
```python
# Model step
def step(self):
    self.shuffle_agents()
    self.do_each("step")
```

Simultaneous activation:
```python
def step(self):
    self.do_each("step")
    self.do_each("advance")
```

Random activation by type:
```python
def step(self):
    self.shuffle_agents()
    for agent_class in self.agent_types:
        self.shuffle_agents(agent_class)
        self.do_each("step", key=agent_class)
```

2023-06-05 15:42 UTC, subhamonsey commented
@tpike3 , @rht thanks for the helpful suggestions. I implemented the requested changes and simplified the code. Could you please run the workflows again?

2023-06-06 02:14 UTC, rht commented
One last thing, I think it needs a test case. The new code branch is not yet covered.

2023-06-11 18:40 UTC, subhamonsey commented
Hey, I added unit tests and rebased my commit over the latest changes. Please could you run the workflows again? Thank you.

2023-06-13 00:11 UTC, rht commented on tests/test_time.py
> +        for output in self.expected_output[3:]:
I suppose the existing code isn't clear about saying that it checks that the shuffling happens within stages, and not across stages.

2023-06-13 00:12 UTC, rht approved these changes

2023-06-13 09:38 UTC, tpike3 approved these changes

2023-06-13 09:39 UTC, tpike3 commented
Thanks @subhamonsey

2023-06-13 09:39 UTC, merged